# ============================================================
# SaleHop sign tweak -- landscape by default, arrow tip text removed
# ============================================================
#
# Two small changes to the printable sign (from the last update):
#
#   - The sign now opens in Landscape by default instead of Portrait
#     (you can still switch back to Portrait with the toggle).
#   - The "Tip: circle or trace an arrow above with a marker to point
#     the way." line under the arrow is gone -- just the arrow itself
#     now.
#
# Only one file changes this time: app/listing/[id]/sign/SignBuilder.js
#
# Run this from inside your salehop project folder (where package.json
# lives) -- same as every script before this one.

# ---------- Safety check: are we actually in the right folder? ----------
if (-not (Test-Path "package.json")) {
  Write-Host ""
  Write-Host "STOP: There's no package.json in this folder." -ForegroundColor Red
  Write-Host "You need to 'cd' into your actual salehop project folder first," -ForegroundColor Red
  Write-Host "then run this script again from there." -ForegroundColor Red
  Write-Host ""
  Write-Host "Current folder: $PWD" -ForegroundColor Yellow
  exit 1
}
if (-not (Test-Path ".git")) {
  Write-Host ""
  Write-Host "STOP: This folder has package.json but no .git folder," -ForegroundColor Red
  Write-Host "so it isn't connected to your GitHub/Vercel project." -ForegroundColor Red
  Write-Host "Make sure you're in the folder you originally cloned, not a copy." -ForegroundColor Red
  Write-Host ""
  Write-Host "Current folder: $PWD" -ForegroundColor Yellow
  exit 1
}
Write-Host "Found package.json and .git here -- this looks like the right folder." -ForegroundColor Cyan
Write-Host ""

[System.IO.Directory]::SetCurrentDirectory((Get-Location).Path)
Write-Host ""

# ---------- app/listing/[id]/sign/SignBuilder.js ----------
[System.IO.Directory]::CreateDirectory("app/listing/[id]/sign") | Out-Null
$b64_SignBuilder_js = @"
J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgdXNlTWVtbywgdXNlU3RhdGUgfSBmcm9tICdyZWFjdCc7CmltcG9ydCB7IGZvcm1hdFRpbWVSYW5nZSwgZm9ybWF0RGF0ZVJhbmdlIH0gZnJvbSAnQC9saWIvZm9ybWF0JzsKCi8vIFN0YW5kYXJkIHBhcGVyIHNpemVzIGEgc2lnbiBjYW4gYmUgcHJpbnRlZCBvbiwgaW4gaW5jaGVzLCBwb3J0cmFpdAovLyAod2lkdGggeCBoZWlnaHQpIC0tIHN3YXBwZWQgd2hlbiAiTGFuZHNjYXBlIiBpcyBwaWNrZWQgYmVsb3cuICJMYXJnZQovLyBTaWduIiBpc24ndCBhIHBhcGVyIHNpemUgYXQgYWxsIC0tIGl0IHRpbGVzIHRoZSBkZXNpZ24gYWNyb3NzIDYgcmVndWxhcgovLyBsZXR0ZXIgc2hlZXRzIChzZWUgdGhlIHBvc3RlciBzZWN0aW9uIGJlbG93KSBmb3Igc29tZXRoaW5nIGJpZyBlbm91Z2gKLy8gdG8gcmVhZCBmcm9tIHRoZSByb2FkLCB0YXBlZCB0b2dldGhlciBhZnRlcndhcmQuCmNvbnN0IFBBUEVSX1NJWkVTID0gWwogIHsgaWQ6ICdsZXR0ZXInLCBsYWJlbDogJzguNSIgw5cgMTEiJywgdzogOC41LCBoOiAxMSB9LAogIHsgaWQ6ICd0YWJsb2lkJywgbGFiZWw6ICcxMSIgw5cgMTciJywgdzogMTEsIGg6IDE3IH0sCiAgeyBpZDogJ3N1cGVyYicsIGxhYmVsOiAnMTMiIMOXIDE5IicsIHc6IDEzLCBoOiAxOSB9LAogIHsgaWQ6ICdwb3N0ZXInLCBsYWJlbDogJ0xhcmdlIFNpZ24gKHRhcGUgdG9nZXRoZXIpJywgdzogbnVsbCwgaDogbnVsbCB9LApdOwoKY29uc3QgQVJST1dTID0gWwogIHsgaWQ6ICdyaWdodCcsIGxhYmVsOiAn4p6cIFJpZ2h0JywgZGVnOiAwIH0sCiAgeyBpZDogJ2Rvd24nLCBsYWJlbDogJ+KenCBEb3duJywgZGVnOiA5MCB9LAogIHsgaWQ6ICdsZWZ0JywgbGFiZWw6ICfinpwgTGVmdCcsIGRlZzogMTgwIH0sCiAgeyBpZDogJ3VwJywgbGFiZWw6ICfinpwgVXAnLCBkZWc6IDI3MCB9LAogIHsgaWQ6ICdub25lJywgbGFiZWw6ICdObyBBcnJvdycsIGRlZzogMCB9LApdOwoKLy8gQSAiTGFyZ2UgU2lnbiIgaXMgNiBvcmRpbmFyeSBsZXR0ZXIgc2hlZXRzICg4LjV4MTEgZWFjaCkgdGhhdCB0b2dldGhlcgovLyBmb3JtIG9uZSBiaWcgcG9zdGVyIC0tIFBvcnRyYWl0IGFycmFuZ2VzIHRoZW0gMiBhY3Jvc3MgeCAzIGRvd24gKGEKLy8gdGFsbCBiYW5uZXIpLCBMYW5kc2NhcGUgYXJyYW5nZXMgdGhlbSAzIGFjcm9zcyB4IDIgZG93biAoYSB3aWRlIG9uZSkuCi8vIEVhY2ggaW5kaXZpZHVhbCBzaGVldCBzdGlsbCBwcmludHMgYXMgYSBub3JtYWwgcG9ydHJhaXQgbGV0dGVyIHBhZ2UgLS0KLy8gb25seSB0aGUgYXJyYW5nZW1lbnQgKHdoaWNoIHNsaWNlIG9mIHRoZSBiaWcgZGVzaWduIGxhbmRzIG9uIHdoaWNoCi8vIHNoZWV0KSBjaGFuZ2VzIHdpdGggb3JpZW50YXRpb24uCmNvbnN0IFRJTEVfV19JTiA9IDguNTsKY29uc3QgVElMRV9IX0lOID0gMTE7CgpmdW5jdGlvbiBwb3N0ZXJHcmlkKG9yaWVudGF0aW9uKSB7CiAgcmV0dXJuIG9yaWVudGF0aW9uID09PSAnbGFuZHNjYXBlJyA/IHsgY29sczogMywgcm93czogMiB9IDogeyBjb2xzOiAyLCByb3dzOiAzIH07Cn0KCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFNpZ25CdWlsZGVyKHsgc2FsZSwgcXJTdmcgfSkgewogIGNvbnN0IFtvcmllbnRhdGlvbiwgc2V0T3JpZW50YXRpb25dID0gdXNlU3RhdGUoJ2xhbmRzY2FwZScpOwogIGNvbnN0IFthcnJvd0lkLCBzZXRBcnJvd0lkXSA9IHVzZVN0YXRlKCdyaWdodCcpOwogIGNvbnN0IFtwYXBlcklkLCBzZXRQYXBlcklkXSA9IHVzZVN0YXRlKCdsZXR0ZXInKTsKCiAgY29uc3QgYXJyb3cgPSBBUlJPV1MuZmluZCgoYSkgPT4gYS5pZCA9PT0gYXJyb3dJZCkgfHwgQVJST1dTWzBdOwogIGNvbnN0IHBhcGVyID0gUEFQRVJfU0laRVMuZmluZCgocCkgPT4gcC5pZCA9PT0gcGFwZXJJZCkgfHwgUEFQRVJfU0laRVNbMF07CiAgY29uc3QgaXNQb3N0ZXIgPSBwYXBlci5pZCA9PT0gJ3Bvc3Rlcic7CgogIGNvbnN0IGRhdGVSYW5nZSA9IGZvcm1hdERhdGVSYW5nZShzYWxlLnNhbGVfZGF0ZSwgc2FsZS5lbmRfZGF0ZSk7CiAgY29uc3QgdGltZVJhbmdlID0gZm9ybWF0VGltZVJhbmdlKHNhbGUuc3RhcnRfdGltZSwgc2FsZS5lbmRfdGltZSk7CgogIC8vIEZvciB0aGUgMyBmaXhlZCBwYXBlciBzaXplczogdGhlIGFjdHVhbCBwcmludGVkIHdpZHRoL2hlaWdodCBpbgogIC8vIGluY2hlcywgc3dhcHBlZCB3aGVuIExhbmRzY2FwZSBpcyBzZWxlY3RlZC4gRmVkIHRvIGJvdGggdGhlIG9uLXNjcmVlbgogIC8vIHByZXZpZXcgKGFzIGEgdW5pdGxlc3MgYXNwZWN0IHJhdGlvKSBhbmQgdGhlIHByaW50IHJ1bGVzIChhcyByZWFsCiAgLy8gaW5jaGVzKSB2aWEgQ1NTIGN1c3RvbSBwcm9wZXJ0aWVzIC0tIHNlZSAuc2lnbi1zaGVldCBpbiBnbG9iYWxzLmNzcy4KICBjb25zdCBwYXBlckRpbXMgPSB1c2VNZW1vKCgpID0+IHsKICAgIGlmIChpc1Bvc3RlciB8fCAhcGFwZXIudykgcmV0dXJuIG51bGw7CiAgICByZXR1cm4gb3JpZW50YXRpb24gPT09ICdsYW5kc2NhcGUnID8geyB3OiBwYXBlci5oLCBoOiBwYXBlci53IH0gOiB7IHc6IHBhcGVyLncsIGg6IHBhcGVyLmggfTsKICB9LCBbaXNQb3N0ZXIsIHBhcGVyLCBvcmllbnRhdGlvbl0pOwoKICBjb25zdCBncmlkID0gdXNlTWVtbygoKSA9PiBwb3N0ZXJHcmlkKG9yaWVudGF0aW9uKSwgW29yaWVudGF0aW9uXSk7CiAgY29uc3QgdGlsZXMgPSB1c2VNZW1vKCgpID0+IHsKICAgIGNvbnN0IGxpc3QgPSBbXTsKICAgIGZvciAobGV0IHJvdyA9IDA7IHJvdyA8IGdyaWQucm93czsgcm93ICs9IDEpIHsKICAgICAgZm9yIChsZXQgY29sID0gMDsgY29sIDwgZ3JpZC5jb2xzOyBjb2wgKz0gMSkgewogICAgICAgIGxpc3QucHVzaCh7IHJvdywgY29sIH0pOwogICAgICB9CiAgICB9CiAgICByZXR1cm4gbGlzdDsKICB9LCBbZ3JpZF0pOwoKICByZXR1cm4gKAogICAgPD4KICAgICAgey8qIC0tLS0tLS0tLS0gT24tc2NyZWVuIGNvbnRyb2xzIChoaWRkZW4gd2hlbiBwcmludGluZykgLS0tLS0tLS0tLSAqL30KICAgICAgPGRpdiBjbGFzc05hbWU9InNpZ24tb3B0aW9ucyBuby1wcmludCI+CiAgICAgICAgPHAgY2xhc3NOYW1lPSJzaWduLW9wdGlvbnMtbGFiZWwiPk9yaWVudGF0aW9uPC9wPgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaWduLW9wdGlvbnMtcm93Ij4KICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgdHlwZT0iYnV0dG9uIgogICAgICAgICAgICBjbGFzc05hbWU9e2BjaGlwICR7b3JpZW50YXRpb24gPT09ICdwb3J0cmFpdCcgPyAnb24nIDogJyd9YH0KICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0T3JpZW50YXRpb24oJ3BvcnRyYWl0Jyl9CiAgICAgICAgICA+CiAgICAgICAgICAgIPCfk4QgUG9ydHJhaXQKICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgIGNsYXNzTmFtZT17YGNoaXAgJHtvcmllbnRhdGlvbiA9PT0gJ2xhbmRzY2FwZScgPyAnb24nIDogJyd9YH0KICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0T3JpZW50YXRpb24oJ2xhbmRzY2FwZScpfQogICAgICAgICAgPgogICAgICAgICAgICDwn5ODIExhbmRzY2FwZQogICAgICAgICAgPC9idXR0b24+CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxwIGNsYXNzTmFtZT0ic2lnbi1vcHRpb25zLWxhYmVsIj5BcnJvdyBEaXJlY3Rpb248L3A+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InNpZ24tb3B0aW9ucy1yb3ciPgogICAgICAgICAge0FSUk9XUy5tYXAoKGEpID0+ICgKICAgICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICAgIGtleT17YS5pZH0KICAgICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgICAgY2xhc3NOYW1lPXtgY2hpcCAke2Fycm93SWQgPT09IGEuaWQgPyAnb24nIDogJyd9YH0KICAgICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZXRBcnJvd0lkKGEuaWQpfQogICAgICAgICAgICA+CiAgICAgICAgICAgICAge2EuaWQgPT09ICdub25lJyA/ICgKICAgICAgICAgICAgICAgICdObyBBcnJvdycKICAgICAgICAgICAgICApIDogKAogICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgZGlzcGxheTogJ2lubGluZS1ibG9jaycsIHRyYW5zZm9ybTogYHJvdGF0ZSgke2EuZGVnfWRlZylgIH19PuKenDwvc3Bhbj4KICAgICAgICAgICAgICApfQogICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICkpfQogICAgICAgIDwvZGl2PgogICAgICAgIDxwIGNsYXNzTmFtZT0iaGludCIgc3R5bGU9e3sgbWFyZ2luVG9wOiAtNiwgbWFyZ2luQm90dG9tOiA0IH19PgogICAgICAgICAgUG9zdGluZyBzb21ld2hlcmUgdGhhdCBpc24mYXBvczt0IHBvaW50aW5nIHRvd2FyZCB0aGUgc2FsZSAobGlrZSBhIGNvbW11bml0eSBib2FyZCk/IFBpY2sgJnF1b3Q7Tm8KICAgICAgICAgIEFycm93LiZxdW90OwogICAgICAgIDwvcD4KCiAgICAgICAgPHAgY2xhc3NOYW1lPSJzaWduLW9wdGlvbnMtbGFiZWwiPlBhcGVyIFNpemU8L3A+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InNpZ24tb3B0aW9ucy1yb3ciPgogICAgICAgICAge1BBUEVSX1NJWkVTLm1hcCgocCkgPT4gKAogICAgICAgICAgICA8YnV0dG9uCiAgICAgICAgICAgICAga2V5PXtwLmlkfQogICAgICAgICAgICAgIHR5cGU9ImJ1dHRvbiIKICAgICAgICAgICAgICBjbGFzc05hbWU9e2BjaGlwICR7cGFwZXJJZCA9PT0gcC5pZCA/ICdvbicgOiAnJ31gfQogICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHNldFBhcGVySWQocC5pZCl9CiAgICAgICAgICAgID4KICAgICAgICAgICAgICB7cC5sYWJlbH0KICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAgICApKX0KICAgICAgICA8L2Rpdj4KICAgICAgICB7aXNQb3N0ZXIgJiYgKAogICAgICAgICAgPHAgY2xhc3NOYW1lPSJoaW50IiBzdHlsZT17eyBtYXJnaW5Ub3A6IC02IH19PgogICAgICAgICAgICBQcmludHMgYXMge2dyaWQuY29scyAqIGdyaWQucm93c30gc2VwYXJhdGUgbGV0dGVyLXNpemUgcGFnZXMgKHtncmlkLmNvbHN9IGFjcm9zcyDDlyB7Z3JpZC5yb3dzfSBkb3duKS4KICAgICAgICAgICAgUHJpbnQgYWxsIG9mIHRoZW0sIHRoZW4gdGFwZSB0aGVtIHRvZ2V0aGVyIGluIG9yZGVyIHVzaW5nIHRoZSB0aWxlIG51bWJlcnMgaW4gZWFjaCBjb3JuZXIuCiAgICAgICAgICA8L3A+CiAgICAgICAgKX0KICAgICAgICB7IWlzUG9zdGVyICYmICgKICAgICAgICAgIDxwIGNsYXNzTmFtZT0iaGludCIgc3R5bGU9e3sgbWFyZ2luVG9wOiAtNiB9fT4KICAgICAgICAgICAgVGhpcyBzZXRzIHRoZSBwYWdlIHNpemUgZm9yIHByaW50aW5nIG9yIHNhdmluZyBhcyBhIFBERi4gSWYgeW91ciBwcmludGVyIHByb21wdHMgeW91IHRvIGNob29zZSBwYXBlciwKICAgICAgICAgICAgcGljayB0aGUgbWF0Y2hpbmcgc2l6ZSB0aGVyZSB0b28uCiAgICAgICAgICA8L3A+CiAgICAgICAgKX0KCiAgICAgICAgPGJ1dHRvbiB0eXBlPSJidXR0b24iIGNsYXNzTmFtZT0ic2lnbi1wcmludC1idG4iIG9uQ2xpY2s9eygpID0+IHdpbmRvdy5wcmludCgpfSBzdHlsZT17eyBtYXJnaW5Ub3A6IDE0IH19PgogICAgICAgICAg8J+WqO+4jyBQcmludCBUaGlzIFNpZ24KICAgICAgICA8L2J1dHRvbj4KICAgICAgPC9kaXY+CgogICAgICB7LyogLS0tLS0tLS0tLSBQcmludGFibGUgY29udGVudCAtLS0tLS0tLS0tICovfQogICAgICB7IWlzUG9zdGVyICYmIHBhcGVyRGltcyAmJiAoCiAgICAgICAgPD4KICAgICAgICAgIDxzdHlsZT57YEBwYWdlIHsgc2l6ZTogJHtwYXBlckRpbXMud31pbiAke3BhcGVyRGltcy5ofWluOyBtYXJnaW46IDAuMzVpbjsgfWB9PC9zdHlsZT4KICAgICAgICAgIDxkaXYKICAgICAgICAgICAgY2xhc3NOYW1lPSJzaWduLXNoZWV0IgogICAgICAgICAgICBzdHlsZT17eyAnLS1wYXBlci13LWluJzogcGFwZXJEaW1zLncsICctLXBhcGVyLWgtaW4nOiBwYXBlckRpbXMuaCB9fQogICAgICAgICAgPgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ic2lnbi1sb2dvIG1hcmtlci1mb250Ij4KICAgICAgICAgICAgICBTYWxlPHNwYW4+SG9wPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgIDxoMSBjbGFzc05hbWU9InNpZ24tdGl0bGUiPntzYWxlLnRpdGxlfTwvaDE+CiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0ic2lnbi1hZGRyIj7wn5ONIHtzYWxlLmFkZHJlc3N9PC9wPgogICAgICAgICAgICA8cCBjbGFzc05hbWU9InNpZ24tZGF0ZXRpbWUiPgogICAgICAgICAgICAgIHtkYXRlUmFuZ2V9CiAgICAgICAgICAgICAgPGJyIC8+CiAgICAgICAgICAgICAge3RpbWVSYW5nZX0KICAgICAgICAgICAgPC9wPgoKICAgICAgICAgICAge2Fycm93LmlkICE9PSAnbm9uZScgJiYgKAogICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaWduLWFycm93IiBzdHlsZT17eyB0cmFuc2Zvcm06IGByb3RhdGUoJHthcnJvdy5kZWd9ZGVnKWAgfX0+CiAgICAgICAgICAgICAgICDinpwKICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgKX0KCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaWduLXFyIiBkYW5nZXJvdXNseVNldElubmVySFRNTD17eyBfX2h0bWw6IHFyU3ZnIH19IC8+CiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0ic2lnbi1xci1jYXB0aW9uIj5TY2FuIGZvciBwaG90b3MsIGZ1bGwgZGV0YWlscyAmYW1wOyBkaXJlY3Rpb25zPC9wPgogICAgICAgICAgICA8cCBjbGFzc05hbWU9InNpZ24tYnJhbmQiPnNhbGVob3AuYXBwPC9wPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC8+CiAgICAgICl9CgogICAgICB7aXNQb3N0ZXIgJiYgKAogICAgICAgIDw+CiAgICAgICAgICA8c3R5bGU+e2BAcGFnZSB7IHNpemU6ICR7VElMRV9XX0lOfWluICR7VElMRV9IX0lOfWluOyBtYXJnaW46IDAuM2luOyB9YH08L3N0eWxlPgogICAgICAgICAgPGRpdgogICAgICAgICAgICBjbGFzc05hbWU9e2Bwb3N0ZXItd3JhcCBncmlkLWNvbHMtJHtncmlkLmNvbHN9YH0KICAgICAgICAgICAgc3R5bGU9e3sgJy0tdGlsZS13LWluJzogVElMRV9XX0lOLCAnLS10aWxlLWgtaW4nOiBUSUxFX0hfSU4sICctLWNvbHMnOiBncmlkLmNvbHMsICctLXJvd3MnOiBncmlkLnJvd3MgfX0KICAgICAgICAgID4KICAgICAgICAgICAge3RpbGVzLm1hcCgoeyByb3csIGNvbCB9LCBpKSA9PiAoCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRpbGUtcGFnZSIga2V5PXtgJHtyb3d9LSR7Y29sfWB9PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRpbGUtbGFiZWwiPgogICAgICAgICAgICAgICAgICBUaWxlIHtpICsgMX0gb2Yge3RpbGVzLmxlbmd0aH0g4oCUIHJvdyB7cm93ICsgMX0sIGNvbCB7Y29sICsgMX0KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPGRpdgogICAgICAgICAgICAgICAgICBjbGFzc05hbWU9InBvc3Rlci1jYW52YXMiCiAgICAgICAgICAgICAgICAgIHN0eWxlPXt7IGxlZnQ6IGBjYWxjKHZhcigtLXRpbGUtdy1pbikgKiAtJHtjb2x9ICogMWluKWAsIHRvcDogYGNhbGModmFyKC0tdGlsZS1oLWluKSAqIC0ke3Jvd30gKiAxaW4pYCB9fQogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icG9zdGVyLWxvZ28gbWFya2VyLWZvbnQiPgogICAgICAgICAgICAgICAgICAgIFNhbGU8c3Bhbj5Ib3A8L3NwYW4+CiAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICB7YXJyb3cuaWQgIT09ICdub25lJyAmJiAoCiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InBvc3Rlci1hcnJvdyIgc3R5bGU9e3sgdHJhbnNmb3JtOiBgcm90YXRlKCR7YXJyb3cuZGVnfWRlZylgIH19PgogICAgICAgICAgICAgICAgICAgICAg4p6cCiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgICAgICAgIDxoMSBjbGFzc05hbWU9InBvc3Rlci10aXRsZSI+e3NhbGUudGl0bGV9PC9oMT4KICAgICAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJwb3N0ZXItYWRkciI+8J+TjSB7c2FsZS5hZGRyZXNzfTwvcD4KICAgICAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJwb3N0ZXItZGF0ZXRpbWUiPgogICAgICAgICAgICAgICAgICAgIHtkYXRlUmFuZ2V9CiAgICAgICAgICAgICAgICAgICAgPGJyIC8+CiAgICAgICAgICAgICAgICAgICAge3RpbWVSYW5nZX0KICAgICAgICAgICAgICAgICAgPC9wPgogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icG9zdGVyLXFyIiBkYW5nZXJvdXNseVNldElubmVySFRNTD17eyBfX2h0bWw6IHFyU3ZnIH19IC8+CiAgICAgICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0icG9zdGVyLWJyYW5kIj5zYWxlaG9wLmFwcCDigJQgc2NhbiBmb3IgZGV0YWlsczwvcD4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICApKX0KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvPgogICAgICApfQogICAgPC8+CiAgKTsKfQo=
"@
[System.IO.File]::WriteAllBytes("app/listing/[id]/sign/SignBuilder.js", [Convert]::FromBase64String($b64_SignBuilder_js))
Write-Host "Wrote app/listing/[id]/sign/SignBuilder.js" -ForegroundColor Green
Write-Host ""

# ---------- Verify it actually got written ----------
# Test-Path -LiteralPath (not plain Test-Path) because the [id] folder
# name would otherwise be treated as a wildcard pattern by PowerShell.
if (-not (Test-Path -LiteralPath "app/listing/[id]/sign/SignBuilder.js")) {
  Write-Host ""
  Write-Host "STOP: app/listing/[id]/sign/SignBuilder.js did not get written." -ForegroundColor Red
  Write-Host "Nothing was committed. Please re-run this script from the correct folder." -ForegroundColor Red
  exit 1
}
Write-Host "File verified on disk." -ForegroundColor Green
Write-Host ""

Write-Host "File written. Reviewing git status..." -ForegroundColor Cyan
git status

$commit = Read-Host "Type Y and press Enter to commit and push this change (or anything else to stop here)"
if ($commit -eq "Y" -or $commit -eq "y") {
  git add -A
  if ($LASTEXITCODE -ne 0) {
    Write-Host "git add failed -- see the error above. Nothing was committed or pushed." -ForegroundColor Red
    exit 1
  }

  git commit -m "Default sign to landscape and remove the arrow tip text"
  if ($LASTEXITCODE -ne 0) {
    Write-Host "git commit failed -- see the error above (this also happens if there was nothing new to commit). Nothing was pushed." -ForegroundColor Red
    exit 1
  }

  git push
  if ($LASTEXITCODE -ne 0) {
    Write-Host "git push failed -- see the error above. Your changes are committed locally but NOT on GitHub/Vercel yet." -ForegroundColor Red
    exit 1
  }

  Write-Host ""
  Write-Host "Pushed successfully! Vercel should pick this up and deploy automatically." -ForegroundColor Green
} else {
  Write-Host "Stopped before committing. Your file is updated locally -- run git add -A, git commit, git push whenever you are ready." -ForegroundColor Yellow
}
