# SaleHop: basic technical SEO -- sitemap, robots.txt, Event structured data
#
# Why: checked how salehop.app is actually doing in search. It IS indexed
# (searching the site by name finds it fine), but it doesn't show up
# anywhere in results for the searches a real potential user would type
# ("garage sales near me", "garage sale app Indiana", etc.) -- that's
# dominated by long-established sites with years of authority, so this
# alone won't fix that overnight. But a real, concrete gap was found:
# salehop.app had no robots.txt and no sitemap.xml at all (both 404'd),
# meaning Google had no map of your individual listing/ad pages to find
# beyond whatever it stumbles onto on its own -- Browse/Map is a
# single-page app with no plain links to each listing. This fixes that,
# plus adds Event structured data to each listing page so a garage sale
# has a shot at Google's richer event-style results (and Maps' "things
# happening near you"), not just the crowded plain-text results page.
#
# What this adds:
#   * app/sitemap.js -- served automatically at salehop.app/sitemap.xml.
#     Lists the homepage, /contact, every approved listing, and every
#     active ad, so crawlers can actually find them all.
#   * app/robots.js -- served automatically at salehop.app/robots.txt.
#     Points crawlers at the sitemap above and keeps them out of /admin,
#     /api, and /auth (nothing there should show up in search results).
#   * Each listing page (salehop.app/listing/[id]) now includes schema.org
#     Event markup (when/where/what) alongside the Open Graph tags it
#     already had for Facebook sharing.
#   * lib/format.js gets one small new helper (toIsoDateTime) used only by
#     the Event markup above.
#
# No database change, no new npm package. Safe to run any time.
#
# Touches: app/sitemap.js (new), app/robots.js (new),
# app/listing/[id]/page.js, lib/format.js.

if (-not (Test-Path "package.json")) {
    Write-Host "ERROR: package.json not found. Run this script from inside your salehop project folder." -ForegroundColor Red
    exit 1
}
if (-not (Test-Path ".git")) {
    Write-Host "ERROR: .git folder not found. Run this script from inside your salehop project folder." -ForegroundColor Red
    exit 1
}

[System.IO.Directory]::SetCurrentDirectory((Get-Location).Path)


$dir_app_sitemap_js = "app"
[System.IO.Directory]::CreateDirectory($dir_app_sitemap_js) | Out-Null
$b64_app_sitemap_js = @"
aW1wb3J0IHsgY3JlYXRlQ2xpZW50IH0gZnJvbSAnQHN1cGFiYXNlL3N1cGFiYXNlLWpzJzsKaW1wb3J0IHsgU0lURV9VUkwgfSBm
cm9tICdAL2xpYi9zaXRlJzsKCi8vIE5leHQuanMncyBidWlsdC1pbiBzaXRlbWFwIGNvbnZlbnRpb24gLS0gdGhpcyBmaWxlIGlz
IGF1dG9tYXRpY2FsbHkKLy8gc2VydmVkIGF0IHNhbGVob3AuYXBwL3NpdGVtYXAueG1sIHdpdGggbm8gcm91dGUgbmVlZGVkLiBM
aXN0cyBldmVyeQovLyByZWFsLCBwdWJsaWMgVVJMIG9uIHRoZSBzaXRlIHNvIHNlYXJjaCBlbmdpbmVzIGNhbiBhY3R1YWxseSBm
aW5kCi8vIGluZGl2aWR1YWwgbGlzdGluZy9hZCBwYWdlcywgcmF0aGVyIHRoYW4gcmVseWluZyBvbiBzdHVtYmxpbmcgaW50byB0
aGVtCi8vIG9uIHRoZWlyIG93biAtLSBCcm93c2UvTWFwIGlzIGEgc2luZ2xlLXBhZ2UgYXBwIHdpdGggbm8gcGxhaW4gPGEgaHJl
Zj4KLy8gbGlua3MgdG8gZWFjaCBsaXN0aW5nLCBzbyB3aXRob3V0IHRoaXMgYSBjcmF3bGVyIGhhcyBubyBtYXAgb2Ygd2hhdAov
LyBleGlzdHMgYmV5b25kIHRoZSBob21lcGFnZS4KLy8KLy8gVXNlcyB0aGUgcHVibGljIGFub24ga2V5IChub3Qgc2VydmljZS1y
b2xlKSwgdGhlIHNhbWUgcmVzdHJpY3RlZCByZWFkCi8vIGV2ZXJ5IGFub255bW91cyB2aXNpdG9yIGFscmVhZHkgZ2V0cyAtLSBv
bmx5IGFwcHJvdmVkIHNhbGVzIC8gYWN0aXZlCi8vIGFkcyBhcmUgZXZlciBsaXN0ZWQgaGVyZSwgbWF0Y2hpbmcgZXhhY3RseSB3
aGF0J3MgYWN0dWFsbHkgcmVhY2hhYmxlCi8vIGFuZCBtZWFudCB0byBiZSBwdWJsaWMuCmNvbnN0IHN1cGFiYXNlVXJsID0gcHJv
Y2Vzcy5lbnYuTkVYVF9QVUJMSUNfU1VQQUJBU0VfVVJMOwpjb25zdCBzdXBhYmFzZUFub25LZXkgPSBwcm9jZXNzLmVudi5ORVhU
X1BVQkxJQ19TVVBBQkFTRV9BTk9OX0tFWTsKCi8vIEEgc29mdCBjYXAsIG5vdCBhIGhhcmQgcGxhdGZvcm0gbGltaXQgKEdvb2ds
ZSBhY2NlcHRzIHVwIHRvIDUwLDAwMCBVUkxzCi8vIHBlciBzaXRlbWFwIGZpbGUpIC0tIGp1c3QgYSBzYW5lIGNlaWxpbmcgc28g
dGhpcyBjYW4ndCBiYWxsb29uCi8vIHVuZXhwZWN0ZWRseSBiZWZvcmUgdGhlICJubyBhdXRvbWF0aWMgbGlzdGluZyBleHBpcnki
IGZvbGxvdy11cCAoc2VlCi8vIGJ1aWxkIHN0YXR1cyBkb2MpIGlzIGV2ZXIgYWRkcmVzc2VkLgpjb25zdCBNQVhfVVJMU19QRVJf
VFlQRSA9IDIwMDA7CgpleHBvcnQgZGVmYXVsdCBhc3luYyBmdW5jdGlvbiBzaXRlbWFwKCkgewogIGNvbnN0IHN0YXRpY1VybHMg
PSBbCiAgICB7IHVybDogU0lURV9VUkwsIGxhc3RNb2RpZmllZDogbmV3IERhdGUoKSwgY2hhbmdlRnJlcXVlbmN5OiAnZGFpbHkn
LCBwcmlvcml0eTogMSB9LAogICAgeyB1cmw6IGAke1NJVEVfVVJMfS9jb250YWN0YCwgY2hhbmdlRnJlcXVlbmN5OiAnbW9udGhs
eScsIHByaW9yaXR5OiAwLjMgfSwKICBdOwoKICBpZiAoIXN1cGFiYXNlVXJsIHx8ICFzdXBhYmFzZUFub25LZXkpIHsKICAgIC8v
IE5vIFN1cGFiYXNlIGNvbmZpZ3VyZWQgKGUuZy4gYSBwcmV2aWV3IGJ1aWxkIG1pc3NpbmcgZW52IHZhcnMpIC0tCiAgICAvLyBz
dGlsbCByZXR1cm4gdGhlIHN0YXRpYyBwYWdlcyByYXRoZXIgdGhhbiBmYWlsaW5nIHRoZSB3aG9sZSByb3V0ZS4KICAgIHJldHVy
biBzdGF0aWNVcmxzOwogIH0KCiAgY29uc3QgY2xpZW50ID0gY3JlYXRlQ2xpZW50KHN1cGFiYXNlVXJsLCBzdXBhYmFzZUFub25L
ZXksIHsKICAgIGF1dGg6IHsgcGVyc2lzdFNlc3Npb246IGZhbHNlIH0sCiAgfSk7CgogIGNvbnN0IFt7IGRhdGE6IHNhbGVzIH0s
IHsgZGF0YTogYWRzIH1dID0gYXdhaXQgUHJvbWlzZS5hbGwoWwogICAgY2xpZW50CiAgICAgIC5mcm9tKCdzYWxlcycpCiAgICAg
IC5zZWxlY3QoJ2lkLCBjcmVhdGVkX2F0JykKICAgICAgLmVxKCdzdGF0dXMnLCAnYXBwcm92ZWQnKQogICAgICAub3JkZXIoJ2Ny
ZWF0ZWRfYXQnLCB7IGFzY2VuZGluZzogZmFsc2UgfSkKICAgICAgLmxpbWl0KE1BWF9VUkxTX1BFUl9UWVBFKSwKICAgIGNsaWVu
dAogICAgICAuZnJvbSgnYWRzJykKICAgICAgLnNlbGVjdCgnaWQsIGNyZWF0ZWRfYXQnKQogICAgICAuZXEoJ2FjdGl2ZScsIHRy
dWUpCiAgICAgIC5vcmRlcignY3JlYXRlZF9hdCcsIHsgYXNjZW5kaW5nOiBmYWxzZSB9KQogICAgICAubGltaXQoTUFYX1VSTFNf
UEVSX1RZUEUpLAogIF0pOwoKICBjb25zdCBsaXN0aW5nVXJscyA9IChzYWxlcyB8fCBbXSkubWFwKChzYWxlKSA9PiAoewogICAg
dXJsOiBgJHtTSVRFX1VSTH0vbGlzdGluZy8ke3NhbGUuaWR9YCwKICAgIGxhc3RNb2RpZmllZDogc2FsZS5jcmVhdGVkX2F0ID8g
bmV3IERhdGUoc2FsZS5jcmVhdGVkX2F0KSA6IHVuZGVmaW5lZCwKICAgIGNoYW5nZUZyZXF1ZW5jeTogJ3dlZWtseScsCiAgICBw
cmlvcml0eTogMC43LAogIH0pKTsKCiAgY29uc3QgYWRVcmxzID0gKGFkcyB8fCBbXSkubWFwKChhZCkgPT4gKHsKICAgIHVybDog
YCR7U0lURV9VUkx9L2FkLyR7YWQuaWR9YCwKICAgIGxhc3RNb2RpZmllZDogYWQuY3JlYXRlZF9hdCA/IG5ldyBEYXRlKGFkLmNy
ZWF0ZWRfYXQpIDogdW5kZWZpbmVkLAogICAgY2hhbmdlRnJlcXVlbmN5OiAnd2Vla2x5JywKICAgIHByaW9yaXR5OiAwLjUsCiAg
fSkpOwoKICByZXR1cm4gWy4uLnN0YXRpY1VybHMsIC4uLmxpc3RpbmdVcmxzLCAuLi5hZFVybHNdOwp9Cg==
"@
[System.IO.File]::WriteAllBytes("app/sitemap.js", [Convert]::FromBase64String($b64_app_sitemap_js))
Write-Host "Updated app/sitemap.js"

$dir_app_robots_js = "app"
[System.IO.Directory]::CreateDirectory($dir_app_robots_js) | Out-Null
$b64_app_robots_js = @"
aW1wb3J0IHsgU0lURV9VUkwgfSBmcm9tICdAL2xpYi9zaXRlJzsKCi8vIE5leHQuanMncyBidWlsdC1pbiByb2JvdHMgY29udmVu
dGlvbiAtLSB0aGlzIGZpbGUgaXMgYXV0b21hdGljYWxseQovLyBzZXJ2ZWQgYXQgc2FsZWhvcC5hcHAvcm9ib3RzLnR4dCB3aXRo
IG5vIHJvdXRlIG5lZWRlZC4gUG9pbnRzIGNyYXdsZXJzCi8vIGF0IHRoZSBuZXcgc2l0ZW1hcC54bWwgKHNlZSBhcHAvc2l0ZW1h
cC5qcykgYW5kIGtlZXBzIHRoZW0gb3V0IG9mIHRoZQovLyBwYXNzd29yZC1nYXRlZCBhZG1pbiBkYXNoYm9hcmQsIGludGVybmFs
IEFQSSByb3V0ZXMsIGFuZCB0aGUgYXV0aAovLyByZWRpcmVjdCBjYWxsYmFjayAtLSBub25lIG9mIHRob3NlIGFyZSBtZWFudCB0
byBzaG93IHVwIGluIHNlYXJjaAovLyByZXN1bHRzLCBhbmQgdGhlcmUncyBub3RoaW5nIHRoZXJlIHdvcnRoIHNwZW5kaW5nIGNy
YXdsIGJ1ZGdldCBvbi4KZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gcm9ib3RzKCkgewogIHJldHVybiB7CiAgICBydWxlczogewog
ICAgICB1c2VyQWdlbnQ6ICcqJywKICAgICAgYWxsb3c6ICcvJywKICAgICAgZGlzYWxsb3c6IFsnL2FkbWluJywgJy9hZG1pbi8n
LCAnL2FwaS8nLCAnL2F1dGgvJ10sCiAgICB9LAogICAgc2l0ZW1hcDogYCR7U0lURV9VUkx9L3NpdGVtYXAueG1sYCwKICB9Owp9
Cg==
"@
[System.IO.File]::WriteAllBytes("app/robots.js", [Convert]::FromBase64String($b64_app_robots_js))
Write-Host "Updated app/robots.js"

$dir_app_listing__id__page_js = "app/listing/[id]"
[System.IO.Directory]::CreateDirectory($dir_app_listing__id__page_js) | Out-Null
$b64_app_listing__id__page_js = @"
aW1wb3J0IHsgZ2V0U2FsZUZvclNoYXJlIH0gZnJvbSAnQC9saWIvZ2V0U2FsZUZvclNoYXJlJzsKaW1wb3J0IHsgZm9ybWF0VGlt
ZVJhbmdlLCBmb3JtYXREYXRlUmFuZ2UsIHRvSXNvRGF0ZVRpbWUgfSBmcm9tICdAL2xpYi9mb3JtYXQnOwppbXBvcnQgeyBTSVRF
X1VSTCB9IGZyb20gJ0AvbGliL3NpdGUnOwppbXBvcnQgU2hhcmVUb0ZhY2Vib29rQnV0dG9uIGZyb20gJ0AvY29tcG9uZW50cy9T
aGFyZVRvRmFjZWJvb2tCdXR0b24nOwoKLy8gQSByZWFsLCBwdWJsaWMsIGluZGl2aWR1YWxseS1zaGFyZWFibGUgcGFnZSBmb3Ig
b25lIGFwcHJvdmVkIHNhbGUgLS0KLy8gdGhpcyBpcyB3aGF0IG1ha2VzIHRoZSAiU2hhcmUgdG8gRmFjZWJvb2siIGJ1dHRvbiBh
Y3R1YWxseSB3b3JrOiBGYWNlYm9vawovLyBuZWVkcyBhIHJlYWwgVVJMIGl0IGNhbiBmZXRjaCBhbmQgcmVhZCBPcGVuIEdyYXBo
IHRhZ3MgZnJvbSB0byBidWlsZCBhCi8vIG5pY2UgcHJldmlldyAocGhvdG8sIHRpdGxlLCBkZXNjcmlwdGlvbikgaW4gdGhlIHNo
YXJlZCBwb3N0LgovLwovLyBPbmx5IGFwcHJvdmVkIHNhbGVzIGFyZSByZWFjaGFibGUgaGVyZSAoc2VlIGdldFNhbGVGb3JTaGFy
ZSwgd2hpY2ggcmVhZHMKLy8gdGhyb3VnaCB0aGUgc2FtZSBhbm9uIGtleSArIFJMUyBldmVyeSBvdGhlciB2aXNpdG9yIHVzZXMp
IC0tIGEgbGlzdGluZwovLyBzdGlsbCBhd2FpdGluZyByZXZpZXcgaXNuJ3QgcHVibGljIHlldCwgc28gdGhlcmUncyBub3RoaW5n
IHRvIHNoYXJlLgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZ2VuZXJhdGVNZXRhZGF0YSh7IHBhcmFtcyB9KSB7CiAgY29uc3Qgc2Fs
ZSA9IGF3YWl0IGdldFNhbGVGb3JTaGFyZShwYXJhbXMuaWQpOwoKICBpZiAoIXNhbGUpIHsKICAgIHJldHVybiB7IHRpdGxlOiAn
TGlzdGluZyBub3QgZm91bmQg4oCUIFNhbGVIb3AnIH07CiAgfQoKICBjb25zdCBzdW1tYXJ5ID0gYCR7Zm9ybWF0RGF0ZVJhbmdl
KHNhbGUuc2FsZV9kYXRlLCBzYWxlLmVuZF9kYXRlKX0gwrcgJHtmb3JtYXRUaW1lUmFuZ2Uoc2FsZS5zdGFydF90aW1lLCBzYWxl
LmVuZF90aW1lKX0gwrcgJHtzYWxlLmFkZHJlc3N9YDsKICBjb25zdCBkZXNjcmlwdGlvbiA9IHNhbGUuZGVzY3JpcHRpb24gPyBz
YWxlLmRlc2NyaXB0aW9uLnNsaWNlKDAsIDE2MCkgOiBzdW1tYXJ5OwogIGNvbnN0IGltYWdlID0gc2FsZS5waG90b191cmxzICYm
IHNhbGUucGhvdG9fdXJscy5sZW5ndGggPiAwID8gc2FsZS5waG90b191cmxzWzBdIDogbnVsbDsKCiAgcmV0dXJuIHsKICAgIHRp
dGxlOiBgJHtzYWxlLnRpdGxlfSDigJQgU2FsZUhvcGAsCiAgICBkZXNjcmlwdGlvbiwKICAgIG9wZW5HcmFwaDogewogICAgICB0
aXRsZTogc2FsZS50aXRsZSwKICAgICAgZGVzY3JpcHRpb24sCiAgICAgIHVybDogYCR7U0lURV9VUkx9L2xpc3RpbmcvJHtzYWxl
LmlkfWAsCiAgICAgIHNpdGVOYW1lOiAnU2FsZUhvcCcsCiAgICAgIGltYWdlczogaW1hZ2UgPyBbeyB1cmw6IGltYWdlIH1dIDog
dW5kZWZpbmVkLAogICAgfSwKICAgIHR3aXR0ZXI6IHsKICAgICAgY2FyZDogaW1hZ2UgPyAnc3VtbWFyeV9sYXJnZV9pbWFnZScg
OiAnc3VtbWFyeScsCiAgICAgIHRpdGxlOiBzYWxlLnRpdGxlLAogICAgICBkZXNjcmlwdGlvbiwKICAgICAgaW1hZ2VzOiBpbWFn
ZSA/IFtpbWFnZV0gOiB1bmRlZmluZWQsCiAgICB9LAogIH07Cn0KCmV4cG9ydCBkZWZhdWx0IGFzeW5jIGZ1bmN0aW9uIExpc3Rp
bmdQYWdlKHsgcGFyYW1zIH0pIHsKICBjb25zdCBzYWxlID0gYXdhaXQgZ2V0U2FsZUZvclNoYXJlKHBhcmFtcy5pZCk7CgogIGlm
ICghc2FsZSkgewogICAgcmV0dXJuICgKICAgICAgPGRpdiBjbGFzc05hbWU9InNoYXJlLXBhZ2UiPgogICAgICAgIDxkaXYgY2xh
c3NOYW1lPSJzaGFyZS1jYXJkIj4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaGFyZS1sb2dvIG1hcmtlci1mb250Ij4KICAg
ICAgICAgICAgU2FsZTxzcGFuPkhvcDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9InNo
YXJlLWVtcHR5Ij4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImJpZyI+8J+UjTwvZGl2PgogICAgICAgICAgICA8cD5UaGlz
IGxpc3RpbmcgaXNuJmFwb3M7dCBhdmFpbGFibGUuIEl0IG1heSBoYXZlIGJlZW4gcmVtb3ZlZCwgc29sZCBvdXQsIG9yIGlzbiZh
cG9zO3QgYXBwcm92ZWQgeWV0LjwvcD4KICAgICAgICAgICAgPGEgY2xhc3NOYW1lPSJwdWJsaXNoLWJ0biBzaGFyZS1ob21lLWJ0
biIgaHJlZj0iLyI+CiAgICAgICAgICAgICAgQnJvd3NlIFNhbGVzIG9uIFNhbGVIb3Ag4oaSCiAgICAgICAgICAgIDwvYT4KICAg
ICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgICk7CiAgfQoKICBjb25zdCBjb3ZlciA9IHNhbGUu
cGhvdG9fdXJscyAmJiBzYWxlLnBob3RvX3VybHMubGVuZ3RoID4gMCA/IHNhbGUucGhvdG9fdXJsc1swXSA6IG51bGw7CiAgY29u
c3QgbGlzdGluZ1VybCA9IGAke1NJVEVfVVJMfS9saXN0aW5nLyR7c2FsZS5pZH1gOwoKICAvLyBzY2hlbWEub3JnIEV2ZW50IG1h
cmt1cCAtLSBsZXRzIGEgZ2FyYWdlIHNhbGUgcG90ZW50aWFsbHkgc2hvdyB1cCBpbgogIC8vIEdvb2dsZSdzIHJpY2hlciBldmVu
dCByZXN1bHRzIChhbmQgTWFwcycgInRoaW5ncyBoYXBwZW5pbmcgbmVhciB5b3UiKQogIC8vIGluc3RlYWQgb2YgY29tcGV0aW5n
IHB1cmVseSBvbiB0aGUgY3Jvd2RlZCBwbGFpbi10ZXh0ICJnYXJhZ2Ugc2FsZXMKICAvLyBuZWFyIG1lIiByZXN1bHRzIHBhZ2Uu
IE5vIG9mZmVyL29yZ2FuaXplciBjbGFpbWVkIGhlcmUgLS0gU2FsZUhvcAogIC8vIGhvc3RzIHRoZSBsaXN0aW5nIGJ1dCBkb2Vz
bid0IHJ1biB0aGUgc2FsZSBpdHNlbGYsIHNvIG9ubHkgdGhlIGZhY3RzCiAgLy8gYWN0dWFsbHkgb24gZmlsZSAod2hlbiwgd2hl
cmUsIHdoYXQpIGFyZSBhc3NlcnRlZC4KICBjb25zdCBldmVudEpzb25MZCA9IHsKICAgICdAY29udGV4dCc6ICdodHRwczovL3Nj
aGVtYS5vcmcnLAogICAgJ0B0eXBlJzogJ0V2ZW50JywKICAgIG5hbWU6IHNhbGUudGl0bGUsCiAgICBkZXNjcmlwdGlvbjogc2Fs
ZS5kZXNjcmlwdGlvbiB8fCBgJHtmb3JtYXREYXRlUmFuZ2Uoc2FsZS5zYWxlX2RhdGUsIHNhbGUuZW5kX2RhdGUpfSDCtyAke3Nh
bGUuYWRkcmVzc31gLAogICAgc3RhcnREYXRlOiB0b0lzb0RhdGVUaW1lKHNhbGUuc2FsZV9kYXRlLCBzYWxlLnN0YXJ0X3RpbWUp
LAogICAgZW5kRGF0ZTogdG9Jc29EYXRlVGltZShzYWxlLmVuZF9kYXRlIHx8IHNhbGUuc2FsZV9kYXRlLCBzYWxlLmVuZF90aW1l
KSwKICAgIGV2ZW50U3RhdHVzOiAnaHR0cHM6Ly9zY2hlbWEub3JnL0V2ZW50U2NoZWR1bGVkJywKICAgIGV2ZW50QXR0ZW5kYW5j
ZU1vZGU6ICdodHRwczovL3NjaGVtYS5vcmcvT2ZmbGluZUV2ZW50QXR0ZW5kYW5jZU1vZGUnLAogICAgbG9jYXRpb246IHsKICAg
ICAgJ0B0eXBlJzogJ1BsYWNlJywKICAgICAgbmFtZTogc2FsZS50aXRsZSwKICAgICAgYWRkcmVzczogewogICAgICAgICdAdHlw
ZSc6ICdQb3N0YWxBZGRyZXNzJywKICAgICAgICBzdHJlZXRBZGRyZXNzOiBzYWxlLmFkZHJlc3MsCiAgICAgIH0sCiAgICAgIC4u
LihOdW1iZXIuaXNGaW5pdGUoc2FsZS5sYXQpICYmIE51bWJlci5pc0Zpbml0ZShzYWxlLmxuZykKICAgICAgICA/IHsgZ2VvOiB7
ICdAdHlwZSc6ICdHZW9Db29yZGluYXRlcycsIGxhdGl0dWRlOiBzYWxlLmxhdCwgbG9uZ2l0dWRlOiBzYWxlLmxuZyB9IH0KICAg
ICAgICA6IHt9KSwKICAgIH0sCiAgICAuLi4oY292ZXIgPyB7IGltYWdlOiBbY292ZXJdIH0gOiB7fSksCiAgICB1cmw6IGxpc3Rp
bmdVcmwsCiAgfTsKCiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPSJzaGFyZS1wYWdlIj4KICAgICAgey8qIGVzbGludC1k
aXNhYmxlLW5leHQtbGluZSByZWFjdC9uby1kYW5nZXIgKi99CiAgICAgIDxzY3JpcHQKICAgICAgICB0eXBlPSJhcHBsaWNhdGlv
bi9sZCtqc29uIgogICAgICAgIGRhbmdlcm91c2x5U2V0SW5uZXJIVE1MPXt7IF9faHRtbDogSlNPTi5zdHJpbmdpZnkoZXZlbnRK
c29uTGQpIH19CiAgICAgIC8+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaGFyZS1jYXJkIj4KICAgICAgICA8ZGl2IGNsYXNzTmFt
ZT0ic2hhcmUtbG9nbyBtYXJrZXItZm9udCI+CiAgICAgICAgICBTYWxlPHNwYW4+SG9wPC9zcGFuPgogICAgICAgIDwvZGl2PgoK
ICAgICAgICB7Y292ZXIgJiYgKAogICAgICAgICAgLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lIEBuZXh0L25leHQvbm8taW1n
LWVsZW1lbnQKICAgICAgICAgIDxpbWcgc3JjPXtjb3Zlcn0gYWx0PSIiIGNsYXNzTmFtZT0ic2hhcmUtY292ZXIiIC8+CiAgICAg
ICAgKX0KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9InNoYXJlLWJvZHkiPgogICAgICAgICAge3NhbGUuaXNfbmVpZ2hib3Job29k
X3NhbGUgJiYgc2FsZS5uZWlnaGJvcmhvb2RfbmFtZSAmJiAoCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJuZWlnaGJvcmhv
b2QtYmFkZ2UiIHN0eWxlPXt7IG1hcmdpbkJvdHRvbTogMTAgfX0+CiAgICAgICAgICAgICAg8J+PmO+4jyBQYXJ0IG9mIHtzYWxl
Lm5laWdoYm9yaG9vZF9uYW1lfQogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICl9CgogICAgICAgICAgPGgxIGNsYXNzTmFt
ZT0ic2hhcmUtdGl0bGUiPntzYWxlLnRpdGxlfTwvaDE+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InNoYXJlLWFkZHIiPvCfk40g
e3NhbGUuYWRkcmVzc308L3A+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InNoYXJlLW1ldGEiPgogICAgICAgICAgICA8c3BhbiBj
bGFzc05hbWU9InRpbWUtYmFkZ2UgbW9ubyI+CiAgICAgICAgICAgICAge2Zvcm1hdERhdGVSYW5nZShzYWxlLnNhbGVfZGF0ZSwg
c2FsZS5lbmRfZGF0ZSl9IMK3IHtmb3JtYXRUaW1lUmFuZ2Uoc2FsZS5zdGFydF90aW1lLCBzYWxlLmVuZF90aW1lKX0KICAgICAg
ICAgICAgPC9zcGFuPgogICAgICAgICAgPC9wPgoKICAgICAgICAgIHtzYWxlLnRhZ3MgJiYgc2FsZS50YWdzLmxlbmd0aCA+IDAg
JiYgKAogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iY2FyZC1tZXRhIiBzdHlsZT17eyBtYXJnaW5Ub3A6IDEwIH19PgogICAg
ICAgICAgICAgIHtzYWxlLnRhZ3MubWFwKCh0KSA9PiAoCiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRhZyIga2V5
PXt0fT4KICAgICAgICAgICAgICAgICAge3R9CiAgICAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAgICAgKSl9CiAgICAg
ICAgICAgIDwvZGl2PgogICAgICAgICAgKX0KCiAgICAgICAgICB7c2FsZS5kZXNjcmlwdGlvbiAmJiA8cCBjbGFzc05hbWU9InNo
YXJlLWRlc2MiPntzYWxlLmRlc2NyaXB0aW9ufTwvcD59CgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9InNoYXJlLWFjdGlvbnMi
PgogICAgICAgICAgICA8U2hhcmVUb0ZhY2Vib29rQnV0dG9uIHVybD17bGlzdGluZ1VybH0gcXVvdGU9e3NhbGUudGl0bGV9IC8+
CiAgICAgICAgICAgIDxhIGNsYXNzTmFtZT0iY2hpcCBzaGFyZS1ob21lLWxpbmsiIGhyZWY9Ii8iPgogICAgICAgICAgICAgIEJy
b3dzZSBNb3JlIFNhbGVzIG9uIFNhbGVIb3Ag4oaSCiAgICAgICAgICAgIDwvYT4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwv
ZGl2PgogICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICk7Cn0K
"@
[System.IO.File]::WriteAllBytes("app/listing/[id]/page.js", [Convert]::FromBase64String($b64_app_listing__id__page_js))
Write-Host "Updated app/listing/[id]/page.js"

$dir_lib_format_js = "lib"
[System.IO.Directory]::CreateDirectory($dir_lib_format_js) | Out-Null
$b64_lib_format_js = @"
Ly8gRm9ybWF0dGluZyArIGRhdGUgaGVscGVycyBzaGFyZWQgYnkgdGhlIEJyb3dzZS9NYXAvUG9zdCBzY3JlZW5zLgoKLy8gUG9z
dGdyZXMgcmV0dXJucyBgdGltZWAgY29sdW1ucyBhcyAiSEg6TU06U1MiIHN0cmluZ3MuIEZvcm1hdCBmb3IgZGlzcGxheS4KZXhw
b3J0IGZ1bmN0aW9uIGZvcm1hdFRpbWUoaGhtbXNzKSB7CiAgaWYgKCFoaG1tc3MpIHJldHVybiAnJzsKICBjb25zdCBbaFN0ciwg
bVN0cl0gPSBoaG1tc3Muc3BsaXQoJzonKTsKICBsZXQgaCA9IHBhcnNlSW50KGhTdHIsIDEwKTsKICBjb25zdCBtID0gbVN0ciB8
fCAnMDAnOwogIGNvbnN0IHN1ZmZpeCA9IGggPj0gMTIgPyAnUE0nIDogJ0FNJzsKICBoID0gaCAlIDEyOwogIGlmIChoID09PSAw
KSBoID0gMTI7CiAgcmV0dXJuIGAke2h9OiR7bX0gJHtzdWZmaXh9YDsKfQoKZXhwb3J0IGZ1bmN0aW9uIGZvcm1hdFRpbWVSYW5n
ZShzdGFydCwgZW5kKSB7CiAgcmV0dXJuIGAke2Zvcm1hdFRpbWUoc3RhcnQpfeKAkyR7Zm9ybWF0VGltZShlbmQpfWA7Cn0KCmNv
bnN0IERPVyA9IHsgU1VOOiAwLCBNT046IDEsIFRVRTogMiwgV0VEOiAzLCBUSFU6IDQsIEZSSTogNSwgU0FUOiA2IH07CgovLyBS
ZXR1cm5zIHRoZSBZWVlZLU1NLUREIGRhdGUgc3RyaW5nIGZvciB0aGUgbmV4dCBvY2N1cnJlbmNlIG9mIHRoZSBnaXZlbgovLyB3
ZWVrZGF5IChGcmkvU2F0L1N1biksIGNvdW50aW5nIHRvZGF5IGFzIGEgdmFsaWQgbWF0Y2guCmV4cG9ydCBmdW5jdGlvbiB1cGNv
bWluZ0RhdGVGb3IoZGF5QWJicmV2LCBmcm9tID0gbmV3IERhdGUoKSkgewogIGNvbnN0IHRhcmdldCA9IERPV1tkYXlBYmJyZXZd
OwogIGNvbnN0IGQgPSBuZXcgRGF0ZShmcm9tKTsKICBkLnNldEhvdXJzKDAsIDAsIDAsIDApOwogIGNvbnN0IGRpZmYgPSAodGFy
Z2V0IC0gZC5nZXREYXkoKSArIDcpICUgNzsKICBkLnNldERhdGUoZC5nZXREYXRlKCkgKyBkaWZmKTsKICByZXR1cm4gdG9EYXRl
S2V5KGQpOwp9Cgpjb25zdCBXRUVLREFZX0xBQkVMID0gWydTVU4nLCAnTU9OJywgJ1RVRScsICdXRUQnLCAnVEhVJywgJ0ZSSScs
ICdTQVQnXTsKCi8vIFJldHVybnMgdGhlIG5leHQgYGNvdW50YCBkYXlzIChpbmNsdWRpbmcgdG9kYXkpIGFzCi8vIFt7IGRhdGU6
ICdZWVlZLU1NLUREJywgbGFiZWw6ICdUT0RBWScgfCAnVE9NT1JST1cnIHwgJ0ZSSScgfCAuLi4gfSwgLi4uXS4KLy8gVXNlZCBm
b3IgYm90aCB0aGUgQnJvd3NlIGZpbHRlciBwaWxscyBhbmQgdGhlIFBvc3Qgc2NyZWVuJ3MgZGF0ZSBwaWNrZXIsCi8vIHNvIGFu
eSBkYXkgb2YgdGhlIHdlZWsgLS0gbm90IGp1c3QgRnJpL1NhdC9TdW4gLS0gaGFzIGEgbWF0Y2hpbmcgcGlsbC4KZXhwb3J0IGZ1
bmN0aW9uIG5leHRORGF5cyhjb3VudCA9IDcsIGZyb20gPSBuZXcgRGF0ZSgpKSB7CiAgY29uc3Qgc3RhcnQgPSBuZXcgRGF0ZShm
cm9tKTsKICBzdGFydC5zZXRIb3VycygwLCAwLCAwLCAwKTsKICBjb25zdCBkYXlzID0gW107CiAgZm9yIChsZXQgaSA9IDA7IGkg
PCBjb3VudDsgaSsrKSB7CiAgICBjb25zdCBkID0gbmV3IERhdGUoc3RhcnQpOwogICAgZC5zZXREYXRlKGQuZ2V0RGF0ZSgpICsg
aSk7CiAgICBjb25zdCBsYWJlbCA9IGkgPT09IDAgPyAnVE9EQVknIDogaSA9PT0gMSA/ICdUTVJXJyA6IFdFRUtEQVlfTEFCRUxb
ZC5nZXREYXkoKV07CiAgICBkYXlzLnB1c2goeyBkYXRlOiB0b0RhdGVLZXkoZCksIGxhYmVsIH0pOwogIH0KICByZXR1cm4gZGF5
czsKfQoKZXhwb3J0IGZ1bmN0aW9uIHRvRGF0ZUtleShkYXRlKSB7CiAgY29uc3QgeSA9IGRhdGUuZ2V0RnVsbFllYXIoKTsKICBj
b25zdCBtID0gU3RyaW5nKGRhdGUuZ2V0TW9udGgoKSArIDEpLnBhZFN0YXJ0KDIsICcwJyk7CiAgY29uc3QgZGF5ID0gU3RyaW5n
KGRhdGUuZ2V0RGF0ZSgpKS5wYWRTdGFydCgyLCAnMCcpOwogIHJldHVybiBgJHt5fS0ke219LSR7ZGF5fWA7Cn0KCi8vIFRydWUg
aWYgYGRhdGVLZXlgIChZWVlZLU1NLUREKSBmYWxscyB3aXRoaW4gW3N0YXJ0RGF0ZSwgZW5kRGF0ZV0KLy8gaW5jbHVzaXZlLiBg
ZW5kRGF0ZWAgbWF5IGJlIG51bGwvdW5kZWZpbmVkIC0tIHRoYXQganVzdCBtZWFucyBhCi8vIHNpbmdsZS1kYXkgc2FsZSwgc28g
aXQncyB0cmVhdGVkIGFzIHRoZSBzYW1lIGRheSBhcyBgc3RhcnREYXRlYC4KZXhwb3J0IGZ1bmN0aW9uIGRhdGVJblJhbmdlKGRh
dGVLZXksIHN0YXJ0RGF0ZSwgZW5kRGF0ZSkgewogIGNvbnN0IGVuZCA9IGVuZERhdGUgfHwgc3RhcnREYXRlOwogIHJldHVybiBk
YXRlS2V5ID49IHN0YXJ0RGF0ZSAmJiBkYXRlS2V5IDw9IGVuZDsKfQoKZnVuY3Rpb24gZm9ybWF0U2hvcnREYXRlKGRhdGVLZXkp
IHsKICBpZiAoIWRhdGVLZXkpIHJldHVybiAnJzsKICBjb25zdCBbeSwgbSwgZF0gPSBkYXRlS2V5LnNwbGl0KCctJykubWFwKE51
bWJlcik7CiAgY29uc3QgZGF0ZSA9IG5ldyBEYXRlKHksIG0gLSAxLCBkKTsKICByZXR1cm4gZGF0ZS50b0xvY2FsZURhdGVTdHJp
bmcoJ2VuLVVTJywgeyBtb250aDogJ3Nob3J0JywgZGF5OiAnbnVtZXJpYycgfSk7Cn0KCi8vICJBdWcgMTciIGZvciBhIHNpbmds
ZS1kYXkgc2FsZSwgIkF1ZyAxNyDigJMgQXVnIDE5IiBmb3IgYSBtdWx0aS1kYXkgb25lLgovLyBgZW5kRGF0ZWAgbWF5IGJlIG51
bGwvdW5kZWZpbmVkL2VxdWFsIHRvIGBzdGFydERhdGVgIC0tIGFsbCByZWFkIGFzCi8vIHNpbmdsZS1kYXkuCmV4cG9ydCBmdW5j
dGlvbiBmb3JtYXREYXRlUmFuZ2Uoc3RhcnREYXRlLCBlbmREYXRlKSB7CiAgaWYgKCFlbmREYXRlIHx8IGVuZERhdGUgPT09IHN0
YXJ0RGF0ZSkgcmV0dXJuIGZvcm1hdFNob3J0RGF0ZShzdGFydERhdGUpOwogIHJldHVybiBgJHtmb3JtYXRTaG9ydERhdGUoc3Rh
cnREYXRlKX0g4oCTICR7Zm9ybWF0U2hvcnREYXRlKGVuZERhdGUpfWA7Cn0KCi8vICIzaCBhZ28iIC8gIjJkIGFnbyIgc3R5bGUg
cmVsYXRpdmUgdGltZXN0YW1wIC0tIHVzZWQgYnkgdGhlIHNwb3R0ZWQtc2FsZQovLyBsaXN0IGNhcmRzIGFuZCBkZXRhaWwgc2hl
ZXQgKGEgc2lnaHRpbmcgZG9lc24ndCBoYXZlIGEgc2FsZV9kYXRlIHRvIHNob3cKLy8gbGlrZSBhIHJlYWwgbGlzdGluZyBkb2Vz
LCBqdXN0ICJ3aGVuIHdhcyB0aGlzIGxhc3QgcmVwb3J0ZWQvYWRkZWQiKS4KZXhwb3J0IGZ1bmN0aW9uIGZvcm1hdFJlbGF0aXZl
VGltZShpc28pIHsKICBpZiAoIWlzbykgcmV0dXJuICcnOwogIGNvbnN0IGRpZmZNcyA9IERhdGUubm93KCkgLSBuZXcgRGF0ZShp
c28pLmdldFRpbWUoKTsKICBjb25zdCBtaW51dGVzID0gTWF0aC5yb3VuZChkaWZmTXMgLyA2MDAwMCk7CiAgaWYgKG1pbnV0ZXMg
PCAxKSByZXR1cm4gJ2p1c3Qgbm93JzsKICBpZiAobWludXRlcyA8IDYwKSByZXR1cm4gYCR7bWludXRlc31tIGFnb2A7CiAgY29u
c3QgaG91cnMgPSBNYXRoLnJvdW5kKG1pbnV0ZXMgLyA2MCk7CiAgaWYgKGhvdXJzIDwgMjQpIHJldHVybiBgJHtob3Vyc31oIGFn
b2A7CiAgY29uc3QgZGF5cyA9IE1hdGgucm91bmQoaG91cnMgLyAyNCk7CiAgcmV0dXJuIGAke2RheXN9ZCBhZ29gOwp9CgovLyBD
b21iaW5lcyBhIGBZWVlZLU1NLUREYCBkYXRlIGFuZCBgSEg6TU06U1NgIHRpbWUgKFBvc3RncmVzJ3Mgb3duIHN0b3JhZ2UKLy8g
Zm9ybWF0cyBmb3Igc2FsZV9kYXRlL3N0YXJ0X3RpbWUvZW5kX3RpbWUpIGludG8gYSBwbGFpbiBJU08gODYwMQovLyBkYXRldGlt
ZSBzdHJpbmcgd2l0aCBubyB0aW1lem9uZSBvZmZzZXQgLS0gZS5nLiAiMjAyNi0wOC0xN1QwOTowMDowMCIuCi8vIFVzZWQgb25s
eSBmb3IgdGhlIGxpc3RpbmcgcGFnZSdzIHNjaGVtYS5vcmcgRXZlbnQgc3RydWN0dXJlZCBkYXRhOwovLyBvbWl0dGluZyBhbiBl
eHBsaWNpdCBvZmZzZXQgaXMgdmFsaWQgSVNPIDg2MDEgYW5kIGlzIHJlYWQgYXMgdGhlCi8vIGV2ZW50J3Mgb3duIGxvY2FsIHRp
bWUsIHdoaWNoIGlzIGNvcnJlY3QgaGVyZSBzaW5jZSBldmVyeSBzYWxlIGlzIGEKLy8gcmVhbCwgc2luZ2xlLXRpbWV6b25lIChJ
bmRpYW5hKSBwaHlzaWNhbCBsb2NhdGlvbi4KZXhwb3J0IGZ1bmN0aW9uIHRvSXNvRGF0ZVRpbWUoZGF0ZVN0ciwgdGltZVN0cikg
ewogIGlmICghZGF0ZVN0cikgcmV0dXJuIHVuZGVmaW5lZDsKICBjb25zdCB0aW1lID0gdGltZVN0ciB8fCAnMDA6MDA6MDAnOwog
IHJldHVybiBgJHtkYXRlU3RyfVQke3RpbWV9YDsKfQoKZXhwb3J0IGZ1bmN0aW9uIGRpc3RhbmNlTWlsZXMoYSwgYikgewogIGlm
ICghYSB8fCAhYiB8fCAhTnVtYmVyLmlzRmluaXRlKGEubGF0KSB8fCAhTnVtYmVyLmlzRmluaXRlKGIubGF0KSkgcmV0dXJuIG51
bGw7CiAgY29uc3QgUiA9IDM5NTguODsgLy8gbWlsZXMKICBjb25zdCBkTGF0ID0gKChiLmxhdCAtIGEubGF0KSAqIE1hdGguUEkp
IC8gMTgwOwogIGNvbnN0IGRMbmcgPSAoKGIubG5nIC0gYS5sbmcpICogTWF0aC5QSSkgLyAxODA7CiAgY29uc3QgbGF0MSA9IChh
LmxhdCAqIE1hdGguUEkpIC8gMTgwOwogIGNvbnN0IGxhdDIgPSAoYi5sYXQgKiBNYXRoLlBJKSAvIDE4MDsKICBjb25zdCBoID0K
ICAgIE1hdGguc2luKGRMYXQgLyAyKSAqKiAyICsgTWF0aC5jb3MobGF0MSkgKiBNYXRoLmNvcyhsYXQyKSAqIE1hdGguc2luKGRM
bmcgLyAyKSAqKiAyOwogIGNvbnN0IGMgPSAyICogTWF0aC5hdGFuMihNYXRoLnNxcnQoaCksIE1hdGguc3FydCgxIC0gaCkpOwog
IHJldHVybiBSICogYzsKfQo=
"@
[System.IO.File]::WriteAllBytes("lib/format.js", [Convert]::FromBase64String($b64_lib_format_js))
Write-Host "Updated lib/format.js"


$checkFiles = @(
    "app/sitemap.js",
    "app/robots.js",
    "app/listing/[id]/page.js",
    "lib/format.js"
)
$missing = $checkFiles | Where-Object { -not (Test-Path -LiteralPath $_) }
if ($missing) {
    Write-Host "ERROR: the following files did not get written:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    exit 1
}
Write-Host ""
Write-Host "All files written successfully." -ForegroundColor Green
Write-Host ""
Write-Host "Nothing to do in the Supabase SQL Editor for this one -- it's code only." -ForegroundColor Yellow
Write-Host "After this deploys, you can check it worked by visiting:" -ForegroundColor Yellow
Write-Host "  https://www.salehop.app/robots.txt" -ForegroundColor Yellow
Write-Host "  https://www.salehop.app/sitemap.xml" -ForegroundColor Yellow
Write-Host "(both should load instead of showing an error)." -ForegroundColor Yellow
Write-Host ""

git status

Write-Host ""
$answer = Read-Host "Commit and push these changes now? (Y/N)"
if ($answer -eq "Y" -or $answer -eq "y") {
    git add -A
    if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: git add failed." -ForegroundColor Red; exit 1 }

    $commitMessage = @"
Add sitemap.xml, robots.txt, and Event structured data for SEO

Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01146L7oDTraxR2XyGhaGyrm
"@

    $commitMsgFile = [System.IO.Path]::GetTempFileName()
    [System.IO.File]::WriteAllText($commitMsgFile, $commitMessage)
    git commit -F $commitMsgFile
    $commitExitCode = $LASTEXITCODE
    Remove-Item $commitMsgFile -ErrorAction SilentlyContinue
    if ($commitExitCode -ne 0) { Write-Host "ERROR: git commit failed." -ForegroundColor Red; exit 1 }

    git push
    if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: git push failed." -ForegroundColor Red; exit 1 }

    Write-Host ""
    Write-Host "Done! Changes committed and pushed. Vercel should start deploying shortly." -ForegroundColor Green
} else {
    Write-Host "Skipped commit/push. Your files were updated locally but not committed." -ForegroundColor Yellow
}
